In [64]:
import cv2
import numpy as np

In [65]:
from PIL import Image
im = Image.open("input.png") #Can be many different formats.
pix = im.load()
pixval= im.size[0]* im.size[1]
print pixval

260100


In [66]:
row = im.size[1]
column = im.size=[0]

#if row % 3 == 0 and column % 3 == 0:
#    blksize = 3
#else:
blksize = 2

print blksize

2


In [22]:
def convolve(image, kernel,kernelName):

    # grab the spatial dimensions of the image, along with
    # the spatial dimensions of the kernel
    (iH, iW) = image.shape[:2]
    (kH, kW) = kernel.shape[:2]
 
    # allocate memory for the output image, taking care to
    # "pad" the borders of the input image so the spatial
    # size (i.e., width and height) are not reduced
    pad =  (kW - 1) / 2
    image = cv2.copyMakeBorder(image, pad, pad, pad, pad,
        cv2.BORDER_REPLICATE)
    output = np.zeros((iH, iW), dtype="float32")


# loop over the input image, "sliding" the kernel across
# each (x, y)-coordinate from left-to-right and top to
# bottom

    for y in np.arange(pad, iH + pad):
        for x in np.arange(pad, iW + pad):
            
# extract the ROI of the image by extracting the
# *center* region of the current (x, y)-coordinates, on='title'
# dimensions
            roi = image[y - pad:y + pad + 1, x - pad:x + pad + 1]
               
# perform the actual convolution by taking the
# element-wise multiplicate between the ROI and
# the kernel, then summing the matrix
            k = (roi * kernel).sum()
            Karr.append(k)
        
# store the values of convoluted kernels in an Array

            output[y - pad, x - pad] = k

# rescale the output image to be in the range [0, 255]
#output = rescale_intensity(output, in_range=(0, 255))
#output = (output * 255).astype("uint8")
 
# return the output image
        
    return output

In [23]:
# construct a sharpening filter
sharpen = np.array((
    [0, -1, 0],
    [-1, 5, -1],
    [0, -1, 0]), dtype="int")
#emboss
emboss = np.array((
    [-2,-1,0],
    [-1,1,1],
    [0,1,2]), dtype="int")

#Edge detection
Edge_detection = np.array((
    [0, 1, 0],
    [0, 1, -0.5],
    [0, 0, 0]), dtype="int")
 
#Custom
Custom_detection = np.array((
    [0, -3, 1],
    [-2, 0, 2],
    [-1, 3, 1]), dtype="int")

#Blank
Blank = np.array((
    [0, 0, 0],
    [0, 1, 0],
    [0, 0, 0]), dtype="int")

#Combined V and H Edge Detection
VH = np.array((
    [0, 0, 0],
    [-1, 1, 0],
    [0, -1, 0]), dtype="int")

#Shadow Mask
ShadowMask = np.array((
    [-2, -1, 0],
    [-1, 0, 1],
    [0, 1, 2]), dtype="int")

#Enhancement Mask
EnhancementMask = np.array((
    [1, 2, 1],
    [2, 4, 2],
    [1, 2, 1]), dtype="int")

In [24]:
kernelBank = (
#    ("sharpen", sharpen), #modded
#    ("Edge_detection", Edge_detection), #modded
#    ("emboss",emboss),  #modded
    ("Custom_detection",Custom_detection),
#    ("Blank",Blank),
    ("VH",VH),
    ("ShadowMask",ShadowMask),
    ("EnhancementMask",EnhancementMask),
)

In [25]:
# load the input image and convert it to grayscale
image = cv2.imread('input.png',cv2.IMREAD_COLOR)
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [26]:
#KernelArr = np.array([],[])
a=0
KernelArr = np.array([],dtype="int")

#setup an empty numpy array

for (kernelName, kernel) in kernelBank:
    # apply the kernel to the grayscale image using both
    # our custom `convole` function and OpenCV's `filter2D`
    # function
    Karr=[]
    #empty temporary list array
    
    print("[INFO] applying {} kernel".format(kernelName))
    convoleOutput = convolve(gray, kernel,kernelName)
    opencvOutput = cv2.filter2D(gray, -1, kernel)
    
    #convert list into numpy array    
    KarrNp = np.asarray(Karr)
    print KarrNp
    print len(KarrNp)
    #concaternate all arrays into one single array size will be No. of kernels x length of each array
    KernelArr = np.concatenate((KernelArr,KarrNp),axis=0)

KernelArr=np.split(KernelArr,4)
KernelArr

[INFO] applying Custom_detection kernel
[0 0 0 ..., 0 0 0]
262144
[INFO] applying VH kernel
[0 0 0 ..., 0 0 0]
262144
[INFO] applying ShadowMask kernel
[0 0 0 ..., 0 0 0]
262144
[INFO] applying EnhancementMask kernel
[0 0 0 ..., 0 0 0]
262144


[array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0]),
 array([0, 0, 0, ..., 0, 0, 0])]

In [27]:
#reshape kernel to array like ([1,2,3,4],[1,2,3,4]) etc
KernelArr=np.swapaxes(KernelArr,0,1)

KernelArr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       ..., 
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
from sklearn.cluster import KMeans
import numpy as np

km = km = KMeans(n_clusters=2, 
            init='random', 
            n_init=10, 
            max_iter=1000,
            tol=1e-04,
            random_state=0)

#run K-Clustering on the Array
kmeans_model = km.fit_predict(KernelArr.reshape(-1,4))
#kmeans_model = km.fit_predict(KernelArr)



print kmeans_model
print len(kmeans_model)

[0 0 0 ..., 0 0 0]
262144


In [29]:
x=0
y=0

for z in kmeans_model:
    if y==im.size[0]:
        y=0
        x=x+1
                
    if z == 1:    
        pix[y,x] = 255 # Set the RGBA Value of the image (tuple)
        
   # else:
   #     pix[y,x] = 0
        
    y=y+1    
                   
im.save("InputO.jpg")
print ("Output Successful")

Output Successful
